# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

# SEO settings
title: Dot-Slash-CS
description: "A computer science club at Ohlone College."
keywords: "computer, science, Ohlone, College, Ohlone College, Computer Science, ./CS, dot-slash-cs, dotslashcs, cs"

# Site settings
url: http://dot-slash-cs.club
baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : ./ComputerScience
  job       : Computer Science Club at Ohlone College
  bio       : "We are a group of computer science students at Ohlone College who have created a cohesive, inclusive community with limitless potential!"
  thumb     : /images/author.jpg
  email     : cout@dot-slash-cs.club
  url       : http://dot-slash-cs.club
  github    : http://github.com/dot-slash-CS
  twitter   : 
  facebook  : http://facebook.com/groups/DotSlashCS/
  linkedin  : 
